SET SQL DIALECT 3;
SET NAMES UTF8;

-- Dados para validar listagens, quitação, dashboard e relatório.
-- Precisa já existir pelo menos um usuário (ERP_Financeiro.exe /setup).
--
-- isql -q -i CARTSYS_dados_teste.sql localhost:C:\CartSys\Database\CARTSYS.FDB -user SYSDBA -password masterkey
-- Ajuste o caminho do .fdb se o seu for outro.

SET TERM ^ ;

EXECUTE BLOCK AS
  DECLARE V_USU BIGINT;
  DECLARE C1 BIGINT;
  DECLARE C2 BIGINT;
  DECLARE C3 BIGINT;
  DECLARE C4 BIGINT;
  DECLARE P1 BIGINT;
  DECLARE P2 BIGINT;
  DECLARE P3 BIGINT;
  DECLARE P4 BIGINT;
  DECLARE P5 BIGINT;
  DECLARE P6 BIGINT;
  DECLARE V BIGINT;
BEGIN
  SELECT MIN(ID) FROM USUARIO INTO :V_USU;
  IF (V_USU IS NULL) THEN
    EXCEPTION E_VENDA_SEM_ITENS 'Crie o administrador (ERP_Financeiro.exe /setup) antes de carregar os dados de teste.';

  IF (EXISTS (SELECT 1 FROM CLIENTE WHERE CPF_CNPJ = '52998224725')) THEN
    EXIT;

  INSERT INTO CLIENTE (NOME, TIPO_PESSOA, CPF_CNPJ, EMAIL, TELEFONE, CEP, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF)
  VALUES ('Ana Souza', 'F', '52998224725', 'ana.souza@exemplo.com', '11987654321', '01310100', 'Av. Paulista', '1000', 'Bela Vista', 'São Paulo', 'SP')
  RETURNING ID INTO :C1;

  INSERT INTO CLIENTE (NOME, TIPO_PESSOA, CPF_CNPJ, EMAIL, TELEFONE, CEP, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF)
  VALUES ('João da Silva', 'F', '39053344705', 'joao.silva@exemplo.com', '21988887777', '20040002', 'Rua da Assembleia', '10', 'Centro', 'Rio de Janeiro', 'RJ')
  RETURNING ID INTO :C2;

  INSERT INTO CLIENTE (NOME, TIPO_PESSOA, CPF_CNPJ, EMAIL, TELEFONE, CEP, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF)
  VALUES ('Mercado São José Ltda', 'J', '11222333000181', 'compras@saojose.com', '3133334444', '30130100', 'Av. Afonso Pena', '500', 'Centro', 'Belo Horizonte', 'MG')
  RETURNING ID INTO :C3;

  INSERT INTO CLIENTE (NOME, TIPO_PESSOA, CPF_CNPJ, EMAIL, TELEFONE, CEP, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF)
  VALUES ('Clínica Boa Vista', 'J', '44555666000172', 'financeiro@boavista.com', '4199991111', '80010000', 'Rua XV de Novembro', '200', 'Centro', 'Curitiba', 'PR')
  RETURNING ID INTO :C4;

  INSERT INTO PRODUTO (CODIGO, DESCRICAO, UNIDADE, PRECO_VENDA) VALUES ('CAF001', 'Café torrado 500g', 'UN', 28.90) RETURNING ID INTO :P1;
  INSERT INTO PRODUTO (CODIGO, DESCRICAO, UNIDADE, PRECO_VENDA) VALUES ('AGU001', 'Água mineral 1,5L', 'UN', 4.50) RETURNING ID INTO :P2;
  INSERT INTO PRODUTO (CODIGO, DESCRICAO, UNIDADE, PRECO_VENDA) VALUES ('CAD001', 'Caderno universitário 10 matérias', 'UN', 19.90) RETURNING ID INTO :P3;
  INSERT INTO PRODUTO (CODIGO, DESCRICAO, UNIDADE, PRECO_VENDA) VALUES ('CAN001', 'Caneta esferográfica azul', 'UN', 2.40) RETURNING ID INTO :P4;
  INSERT INTO PRODUTO (CODIGO, DESCRICAO, UNIDADE, PRECO_VENDA) VALUES ('RES001', 'Resma de papel A4 500 folhas', 'UN', 32.00) RETURNING ID INTO :P5;
  INSERT INTO PRODUTO (CODIGO, DESCRICAO, UNIDADE, PRECO_VENDA) VALUES ('MOU001', 'Mouse óptico USB', 'UN', 49.90) RETURNING ID INTO :P6;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C1, :V_USU, DATEADD(-70 DAY TO CURRENT_TIMESTAMP), DATEADD(-55 DAY TO CURRENT_DATE), 1, 10.00, 'Pedido recorrente')
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P1, 10, 28.90, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 2, :P2, 24, 4.50, 0);
  UPDATE VENDA SET STATUS = 2 WHERE ID = :V;
  INSERT INTO RECEBIMENTO (VENDA_ID, DT_RECEBIMENTO, VL_RECEBIDO, FORMA_PAGAMENTO, USUARIO_ID, OBSERVACAO)
  SELECT ID, DATEADD(-68 DAY TO CURRENT_TIMESTAMP), VL_TOTAL, 1, :V_USU, 'Dinheiro' FROM VENDA WHERE ID = :V;
  UPDATE VENDA SET STATUS = 3 WHERE ID = :V;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C3, :V_USU, DATEADD(-45 DAY TO CURRENT_TIMESTAMP), DATEADD(-30 DAY TO CURRENT_DATE), 1, 0, 'Compra mensal')
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P5, 8, 32.00, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 2, :P3, 20, 19.90, 5.00);
  UPDATE VENDA SET STATUS = 2 WHERE ID = :V;
  INSERT INTO RECEBIMENTO (VENDA_ID, DT_RECEBIMENTO, VL_RECEBIDO, FORMA_PAGAMENTO, USUARIO_ID, OBSERVACAO)
  SELECT ID, DATEADD(-43 DAY TO CURRENT_TIMESTAMP), VL_TOTAL, 4, :V_USU, 'Boleto' FROM VENDA WHERE ID = :V;
  UPDATE VENDA SET STATUS = 3 WHERE ID = :V;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C2, :V_USU, DATEADD(-20 DAY TO CURRENT_TIMESTAMP), DATEADD(-5 DAY TO CURRENT_DATE), 1, 0, NULL)
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P6, 2, 49.90, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 2, :P4, 12, 2.40, 0);
  UPDATE VENDA SET STATUS = 2 WHERE ID = :V;
  INSERT INTO RECEBIMENTO (VENDA_ID, DT_RECEBIMENTO, VL_RECEBIDO, FORMA_PAGAMENTO, USUARIO_ID, OBSERVACAO)
  SELECT ID, DATEADD(-18 DAY TO CURRENT_TIMESTAMP), VL_TOTAL, 2, :V_USU, 'PIX' FROM VENDA WHERE ID = :V;
  UPDATE VENDA SET STATUS = 3 WHERE ID = :V;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C4, :V_USU, DATEADD(-8 DAY TO CURRENT_TIMESTAMP), DATEADD(5 DAY TO CURRENT_DATE), 1, 15.00, 'Kit escritório')
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P5, 4, 32.00, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 2, :P6, 3, 49.90, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 3, :P3, 6, 19.90, 0);
  UPDATE VENDA SET STATUS = 2 WHERE ID = :V;
  INSERT INTO RECEBIMENTO (VENDA_ID, DT_RECEBIMENTO, VL_RECEBIDO, FORMA_PAGAMENTO, USUARIO_ID, OBSERVACAO)
  SELECT ID, DATEADD(-7 DAY TO CURRENT_TIMESTAMP), VL_TOTAL, 3, :V_USU, 'Cartão' FROM VENDA WHERE ID = :V;
  UPDATE VENDA SET STATUS = 3 WHERE ID = :V;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C1, :V_USU, DATEADD(-3 DAY TO CURRENT_TIMESTAMP), DATEADD(10 DAY TO CURRENT_DATE), 1, 0, 'Aguardando pagamento')
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P1, 4, 28.90, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 2, :P2, 12, 4.50, 0);
  UPDATE VENDA SET STATUS = 2 WHERE ID = :V;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C3, :V_USU, DATEADD(-1 DAY TO CURRENT_TIMESTAMP), DATEADD(14 DAY TO CURRENT_DATE), 1, 0, 'Pendente para quitação')
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P5, 2, 32.00, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 2, :P4, 50, 2.40, 0);
  UPDATE VENDA SET STATUS = 2 WHERE ID = :V;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C2, :V_USU, DATEADD(-12 DAY TO CURRENT_TIMESTAMP), DATEADD(-1 DAY TO CURRENT_DATE), 1, 0, NULL)
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P6, 1, 49.90, 0);
  UPDATE VENDA SET STATUS = 2 WHERE ID = :V;
  UPDATE VENDA SET STATUS = 4, MOTIVO_CANCELAMENTO = 'Cliente desistiu da compra', USUARIO_CANCEL_ID = :V_USU
   WHERE ID = :V;

  INSERT INTO VENDA (CLIENTE_ID, USUARIO_ID, DT_EMISSAO, DT_VENCIMENTO, STATUS, VL_DESCONTO, OBSERVACAO)
  VALUES (:C4, :V_USU, CURRENT_TIMESTAMP, DATEADD(20 DAY TO CURRENT_DATE), 1, 0, 'Ainda em digitação')
  RETURNING ID INTO :V;
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 1, :P3, 3, 19.90, 0);
  INSERT INTO VENDA_ITEM (VENDA_ID, SEQ, PRODUTO_ID, QUANTIDADE, PRECO_UNIT, VL_DESCONTO) VALUES (:V, 2, :P1, 2, 28.90, 0);
END^

SET TERM ; ^
COMMIT;
